resilience4j:
  retry:
      instances:
        passengerService:
          maxRetryAttempts: 10
          waitDuration: 1s

spring:
  application:
    name: PassengerService
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true