server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
      - id: billingService
        uri: http://localhost:8081/
        predicates:
        - Path=/billing/**
      - id: passengerService
        uri: http://localhost:8082/
        predicates:
        - Path=/perssenger/**