server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
      - id: billingService
        uri: http://192.168.1.5:8080/
        predicates:
        - Path=/billing/**
      - id: passengerService
        uri: http://192.168.1.5:8081/
        predicates:
        - Path=/perssengers/**